name: mtefa
description: "This is a Flutter POS (Point of Sale) system with multi-brand support, stock control, and activity tracking. The application uses Restful API for backend services and implements Clean Architecture with responsive design patterns. Local Database will be Drift (SQLite)"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  http: ^1.2.0
  flutter_secure_storage: ^9.2.2
  
  provider: ^6.1.2
  
  get_it: ^7.6.7
  
  flutter_dotenv: ^5.1.0
  
  # Database
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.20
  sqlite3: ^2.4.2
  path_provider: ^2.1.3
  path: ^1.9.0
  
  # Utilities
  equatable: ^2.0.5
  connectivity_plus: ^6.0.1
  easy_localization: ^3.0.8
  dropdown_button2: ^2.3.9
  intl: ^0.20.2
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  
  # Code generation for Drift
  drift_dev: ^2.18.0
  build_runner: ^2.4.12
  
  # Testing dependencies
  mockito: ^5.4.4
  faker: ^2.1.0
  test: ^1.25.2
  
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lang/
    - assets/images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
